### ISSUE TITLE
Hide namespaces/projects dropdown on Edit Broker Page and Details Page

### ISSUE THREAD

**Issue by ajaypratap003** [artemiscloud/activemq-artemis-self-provisioning-plugin#109]
Hide namespaces/projects dropdown on Edit Broker Page and Details Page

**Comment by lavocatt** [comment]
Is it something we can easily do?

**Comment by lavocatt** [comment]
After a thorough examination of the console and the various pages it has, I don't think this is something we want to do, as it would make our custom pages diverge from the standard.

**Comment by Msarawan** [comment]
> After a thorough examination of the console and the various pages it has, I don't think this is something we want to do, as it would make our custom pages diverge from the standard.

+1
