### ISSUE TITLE
Documentation: questions about CORS related issue

### ISSUE THREAD

**Issue by lavocatt** [artemiscloud/activemq-artemis-self-provisioning-plugin#144]
As @RoddieKieley asks in #120:

> Should the user expect any CORS related issues connecting to jolokia with the current plugin/operator/broker container images available at quay.io/artemiscloud? I think the answer is no, right?

**Comment by gaohoward** [comment]
No. Becuase we moved jolokia access into backend api-server which is not restricted by CORs check as in a web browser.
