### ISSUE TITLE
Deprecation warnings in the CI (December the 5th 2024 is the last deadline for one of these)

### ISSUE THREAD

**Issue by lavocatt** [artemiscloud/activemq-artemis-self-provisioning-plugin#153]
These needs to be updated:

![image](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/assets/86971992/dcdda3b2-0e8a-4213-9b5f-1e30dc918ce9)

**Comment by Msarawan** [comment]
Closed as completed via [PR#329](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/pull/329)
