### ISSUE TITLE
The new button to add annotations & connectors doesn't work properly

### ISSUE THREAD

**Issue by lavocatt** [artemiscloud/activemq-artemis-self-provisioning-plugin#173]
When the user hover the + button, the mouse pointer doesn't change to a clickable pointer.
![image](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/assets/86971992/dd1eed94-2591-457e-8b21-03b70fcfd494)

Can you fix this @Msarawan please?

**Comment by Msarawan** [comment]
> When the user hover the + button, the mouse pointer doesn't change to a clickable pointer. ![image](https://private-user-images.githubusercontent.com/86971992/340285833-dd1eed94-2591-457e-8b21-03b70fcfd494.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTE1ODQsIm5iZiI6MTcxODY5MTI4NCwicGF0aCI6Ii84Njk3MTk5Mi8zNDAyODU4MzMtZGQxZWVkOTQtMjU5MS00NTdlLThiMjEtMDNiNzBmY2ZkNDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA2MTQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZGY2N2E5ZWE1YTI5YmQ0NGJlOGM2YzVlZDYwYzI4NTUwMzcyNTcwOTQ5ZDk5ZGQ4NjI1YmRjN2RiMjliNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ozGyqiPlHALdsnBWRu2VS4qhZMj3f6-TEgs1sh5uQ94)
> 
> Can you fix this @Msarawan please?

sure, i will fix it.

**Comment by Msarawan** [comment]
> When the user hover the + button, the mouse pointer doesn't change to a clickable pointer. ![image](https://private-user-images.githubusercontent.com/86971992/340285833-dd1eed94-2591-457e-8b21-03b70fcfd494.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3Mzg4NzAsIm5iZiI6MTcxODczODU3MCwicGF0aCI6Ii84Njk3MTk5Mi8zNDAyODU4MzMtZGQxZWVkOTQtMjU5MS00NTdlLThiMjEtMDNiNzBmY2ZkNDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE5MjI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MTQ1ZWI0NWQ2MDA4MDc2ZjZlNzNjYzVlMzc1YzRiYzBmYjFmYzQ1NTIwMWQ0NGYzNDdhYTg4M2I2MzJlOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XrpgRnWYzXvvHu2UBdv40upIhWR2c_J-3okr1kif1bQ)
> 
> Can you fix this @Msarawan please?

Hello @lavocatt , fixed this issue. with [PR #180](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/pull/180) please take a look.

**Comment by Msarawan** [comment]
Closed as completed.
