### ISSUE TITLE
Ssl Enabled switch too big?

### ISSUE THREAD

**Issue by gaohoward** [artemiscloud/activemq-artemis-self-provisioning-plugin#178]
It looks a bit too big among other components in the acceptor/connector/console config page.
Could it be smaller?

**Comment by lavocatt** [comment]
I agree that it is a bit big, maybe there are variants for the switch we can use?

**Comment by gaohoward** [comment]
It looks better now with the new UI layout. Will close this PR.

> I agree that it is a bit big, maybe there are variants for the switch we can use?

For now I think it's fine. In the old UI it is too big.
