### ISSUE TITLE
Production build: UI wrongly says that there is no cert-manager installed

### ISSUE THREAD

**Issue by lavocatt** [artemiscloud/activemq-artemis-self-provisioning-plugin#217]
![image](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/assets/86971992/f246d0b0-b1fd-430c-a08a-fdff926c6e21)

I've tried with the community cert-manager and the downstream cert-manager, the result was the same.
But it's possible to create a chain of trust on preset menu:

![image](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/assets/86971992/401dcfe9-4aa9-41cf-8eaa-d40f57818c91)

We need to figure out the differences between the two of them.

**Comment by lavocatt** [comment]
There's something about how the warning gets computed:

![image](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/assets/86971992/89ec12ab-0757-481f-8ae1-2ad8ef82c93e)

![image](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/assets/86971992/0606e6c0-855a-4408-85f5-41890efe5731)

I think that this might be because we look for the deployment in the  `cert-manager` namespace. Could it be better to search for all namespaces instead? I've noticed on prod that the cert-manager was deployed in the `openshidft-operator` namespace.

Alternatively we can drop the warning for the demo?

**Comment by RoddieKieley** [comment]
Yeah I don't think there's any guarantee that any given user/administrator installed operator will end up in a specific namespace. Likely there are a few things that can be done to make the check more robust, like checking for its CRD's first as the operator won't function without them, then checking the 'standard'/expected namespaces, then widening the search to all namespaces after that.

**Comment by gaohoward** [comment]
The check assumes the user installs the redhat cert-manager from operatorHub. So if the user does use default values, the check would fail. The check needs improvement but it's  useful when in production it will make sure the cert-manager is of the supported version.

![image](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/assets/686319/3542bfc7-121d-4142-85b6-38b9e60dc083)

**Comment by gaohoward** [comment]
Yeah I think Checking the CRDs would be a good idea

**Comment by gaohoward** [comment]
@lavocatt When you use downstream cert-manager, did you check where the 'cert-manager' is really installed?

**Comment by lavocatt** [comment]
> The check assumes the user installs the redhat cert-manager from operatorHub. So if the user does use default values, the check would fail. The check needs improvement but it's useful when in production it will make sure the cert-manager is of the supported version.
> 

We were discussing with @RoddieKieley today about the requirements for the provisioning plugin. And if I understand correctly, we should aim at being compatible with the upstream variants of the various components we depend on.

For instance, the demo cluster is set up with the version `1.31.1` of the community cert-manager and the latest upstream build of the activemq operator (`1.2.3`)

So in that regard, shouldn't we avoid to assume any specific `cert-manager` source build (I mean community vs RH)?

> Yeah I think Checking the CRDs would be a good idea

My thinking would be, we don't check the cluster configuration and we let the user execute the requests whenever.
But then if the request comes back as a failure, either because there's a configuration issue with cert-manager of because cert-manager itself is missing, then we display that error to the user and they can act upon it to fix the setup.

For instance, atm on the demo cluster we're experiencing a disturbance while deploying the community cert-manager. Creating a cert leads to an error:
![image](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/assets/86971992/6f9eaf42-9b24-4780-8788-7f4f12d83202)

This is a situation where static checks can't prevent the functionality to crash.
I'm wondering if every interactions with external components should be treated the same.

> @lavocatt When you use downstream cert-manager, did you check where the 'cert-manager' is really installed?

Not really, I was mainly clicking next next next and was done with it. The downstream always worked. It's just the upstream version that is failing the check.
