### ISSUE TITLE
The `edit settings` button is not doing anything on the settings tabs of brokers details page

### ISSUE THREAD

**Issue by lavocatt** [artemiscloud/activemq-artemis-self-provisioning-plugin#220]
![image](https://github.com/artemiscloud/activemq-artemis-self-provisioning-plugin/assets/86971992/dcc23b93-06f0-42a0-ae81-d34b9c69fb02)

What should we do about this button?

**Comment by gaohoward** [comment]
The configuration page is still a place holder and I don't think there is any real contents implemented here

**Comment by Msarawan** [comment]
The configuration page was initially created to build the wireframe structure, primarily to display some details of the created broker. Therefore, I believe the Edit Settings button is not necessary now, so I plan to remove it.
