### ISSUE TITLE
code quality: rename the type K8sResourceKind to something better

### ISSUE THREAD

**Issue by lavocatt** [artemiscloud/activemq-artemis-self-provisioning-plugin#226]
And also asses its usages. Some looks contradictory.

**Comment by Msarawan** [comment]
> Removing loadash would mean a lot of refactoring for the metrics components. I'm not sure this is worth the effort. We should make sure that we don't use this library for new components as much as possible in the future. Wdyt @Msarawan ? I think we can close this issue.

yeah i agree with your point.
