### ISSUE TITLE
Incorrect Redirect Path on Create and Cancel Buttons in the Edit Broker on Pods List and Broker Details Pages

### ISSUE THREAD

**Issue by Msarawan** [artemiscloud/activemq-artemis-self-provisioning-plugin#239]
When clicking the `Create` or `Cancel` buttons on the `edit-broker`, the redirection should take the user back to the current page from which they navigated (e.g., Pods List page or Broker Details page). However, it currently redirects to the Brokers page instead.

**Comment by lavocatt** [comment]
@Msarawan  I think this issue is fixed right?

**Comment by Msarawan** [comment]
> @Msarawan I think this issue is fixed right?

Yes, the issue is fixed. but still the PR is not merged. we need to do rebasing  and  some cleanup with the PR and then it's good to merge.

**Comment by Msarawan** [comment]
Closed as completed.
