### ISSUE TITLE
Overhaul the integration of the broker creation form within OpenShift

### ISSUE THREAD

**Issue by lavocatt** [artemiscloud/activemq-artemis-self-provisioning-plugin#292]
Right now our form to create a broker is only accessible via the entry point we have on the broker list

![image](https://github.com/user-attachments/assets/c1a61f61-18a8-4724-aea6-17bdaff153b1)

But it turns out that there is another way to create and ActiveMQ Artemis Broker using the search:

![image](https://github.com/user-attachments/assets/7bb9cde0-3d07-4aa0-a7a3-248f69d4e777)

This is showing a button to create the broker, even though it is called an `ActiveMQArtemis`

Clicking on the button opens up the default view to create a broker:
![image](https://github.com/user-attachments/assets/41857e92-7202-472b-b6dc-46197d4fb235)

And instead it should display ours.

In the dynamic plugin reference (https://docs.openshift.com/container-platform/4.13/web_console/dynamic-plugin/dynamic-plugins-reference.html) there is mention of a way to do achieve what we want:

![image](https://github.com/user-attachments/assets/1cfd9ce5-5d55-48a5-a55a-71c1c99eb72f)

Acceptance criteria of the issue:

- [x] Creating a broker using the search or our button in the brokers list display the same broker creation form.
- [ ] We've identified and tested that all these entry points do behave the way we expect them to either via manual testing, or via something different (to be defined, since there is no real way to unit-test the console right now)

**Comment by lavocatt** [comment]
Note that the broker creation form through the installed operator might not be customizable. That's an unknown we need to figure out

**Comment by gaohoward** [comment]
+1.

**Comment by lavocatt** [comment]
I have removed the OLM integration from the requirements of this issue and lower the volume of work needed to M. It might be even an S (depending).

**Comment by lavocatt** [comment]
Thanks to @Msarawan's experimentation we now know that this is easy to solve
