### ISSUE TITLE
Add a separator before `Brokers` in the workload 

### ISSUE THREAD

**Issue by lavocatt** [artemiscloud/activemq-artemis-self-provisioning-plugin#305]
Using

![image](https://github.com/user-attachments/assets/b2885c24-575d-4d4c-acde-69fe798c7233)

**Comment by Msarawan** [comment]
Hello @lavocatt , Thank you for suggesting the new `console.navigation/separator` extension. However, we can achieve the same result by simply adding the `insertAfter`and `insertBefore` properties to our existing `console.navigation/href` extension.

**Comment by lavocatt** [comment]
Yes you are right, let's not add a separator, good finding.
